version: "3"
services:
  ac-demo-videofier:
    build: .
    volumes:
      - ./recordings:/recordings:rw
      - ./conf/demos:/home/user/.assaultcube_v1.2/demos
      - ./conf/maps:/home/user/.assaultcube_v1.2/packages/maps
    environment:
      - OUTPUT_FILE=/recordings/demo.mp4
      - DEMO_NAME=20210725_2254_51.38.185.3_XX_Olympic_TimeRun_GEMA_4min_CTF
      - FOLLOW_CLIENT_NUMBER=0
      - START_TIMESTAMP=267836
      - END_TIMESTAMP=286453
